import { Info, AlertTriangle, CheckCircle } from "lucide-react"
import type { ErrorCode } from "@/lib/deepfake-report-types"

interface ForensicFlagsProps {
  errors: ErrorCode[]
}

interface FlagItem {
  type: "red" | "amber" | "green"
  iconType: "info" | "warning" | "check"
  title: string
  description: string
}

function buildFlags(errors: ErrorCode[]): FlagItem[] {
  if (errors.length === 0) {
    return [
      {
        type: "green",
        iconType: "check",
        title: "No issues detected",
        description: "No errors found",
      },
    ]
  }

  const flags: FlagItem[] = []

  if (errors.includes("DeepfakeDetected")) {
    flags.push({
      type: "red",
      iconType: "info",
      title: "Deepfake detected",
      description: "AI-generated content detected by the model",
    })
  }

  if (errors.includes("MetadataAiGeneratorDetected")) {
    flags.push({
      type: "red",
      iconType: "warning",
      title: "AI generator detected",
      description: "Metadata indicates the video was generated by AI",
    })
  }

  if (errors.includes("MetadataProfessionalSoftware")) {
    flags.push({
      type: "amber",
      iconType: "warning",
      title: "Professional software detected",
      description:
        "Metadata indicates professional editing software (e.g. Adobe After Effects)",
    })
  }

  if (errors.includes("SuspiciousMetadata")) {
    flags.push({
      type: "amber",
      iconType: "warning",
      title: "Suspicious metadata",
      description:
        "Missing camera data, encoding mismatches, or signs of video conversion",
    })
  }

  return flags
}

const flagStyles: Record<string, { bg: string; border: string; titleColor: string; descColor: string; iconColor: string }> = {
  red: { bg: "#FEE2E2", border: "#DC2626", titleColor: "#991B1B", descColor: "#7F1D1D", iconColor: "#DC2626" },
  amber: { bg: "#FEF3C7", border: "#F59E0B", titleColor: "#92400E", descColor: "#78350F", iconColor: "#F59E0B" },
  green: { bg: "#D1FAE5", border: "#10B981", titleColor: "#065F46", descColor: "#047857", iconColor: "#10B981" },
}

function FlagIcon({ type, iconType }: { type: "red" | "amber" | "green"; iconType: "info" | "warning" | "check" }) {
  const s = flagStyles[type]
  if (iconType === "check") return <CheckCircle size={15} color={s.iconColor} style={{ flexShrink: 0, marginTop: 1 }} />
  if (iconType === "warning") return <AlertTriangle size={15} color={s.iconColor} style={{ flexShrink: 0, marginTop: 1 }} />
  return <Info size={15} color={s.iconColor} style={{ flexShrink: 0, marginTop: 1 }} />
}

export function ForensicFlags({ errors }: ForensicFlagsProps) {
  const flags = buildFlags(errors)

  return (
    <div style={{ marginBottom: "10px" }}>
      <div
        style={{
          fontSize: "10px",
          fontWeight: 700,
          color: "#374151",
          textTransform: "uppercase",
          letterSpacing: "0.5px",
          marginBottom: "6px",
        }}
      >
        Forensic Flags
      </div>
      <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
        {flags.map((flag, i) => {
          const s = flagStyles[flag.type]
          return (
            <div
              key={i}
              style={{
                display: "flex",
                alignItems: "flex-start",
                gap: "9px",
                padding: "9px 12px",
                background: s.bg,
                borderLeft: `4px solid ${s.border}`,
                borderRadius: "4px",
              }}
            >
              <FlagIcon type={flag.type} iconType={flag.iconType} />
              <div>
                <div style={{ fontSize: "10px", fontWeight: 700, color: s.titleColor, lineHeight: "1.3" }}>
                  {flag.title}
                </div>
                <div style={{ fontSize: "9px", color: s.descColor, lineHeight: "1.4", marginTop: "2px" }}>
                  {flag.description}
                </div>
              </div>
            </div>
          )
        })}
      </div>
    </div>
  )
}
